export const jobOpeningsInputs = [
  {
    id: 0,
    placeholder: "City",
  },
  {
    id: 1,
    placeholder: "Location",
  },
  {
    id: 3,
    placeholder: "Schedule",
  },
  {
    id: 4,
    placeholder: "Job Location Type",
  },
];

export const notifications = [
  {
    newLabel: "NEW",
    positionTitle: "Red's Diner ",
    description: "#Food & Beverage ",
    location: "620 10 Ave SW #134, Calgary, AB T2R 1C3 ",
    time: "4PM - 10PM (6 Hours)",
    fullTime: "Full-Time ",
    payment: "Payment: ",
    basicEnglish: "Basic English Needed",
    position: "3/5 positions filled",
    imageUrl: "/jobs/item.png",
    rate: "$18/hr",
    startDate: "Start Date: As soon as possible",
    title: "Server",
  },
  {
    newLabel: "NEW",
    positionTitle: "Red's Diner ",
    description: "#Food & Beverage ",
    location: "620 10 Ave SW #134, Calgary, AB T2R 1C3 ",
    time: "4PM - 10PM (6 Hours)",
    fullTime: "Full-Time ",
    payment: "Payment: ",
    basicEnglish: "Basic English Needed",
    position: "3/5 positions filled",
    imageUrl: "/jobs/item.png",
    rate: "$18/hr",
    startDate: "Start Date: As soon as possible",
    title: "Server",
  },
  {
    newLabel: "NEW",
    positionTitle: "Red's Diner ",
    description: "#Food & Beverage ",
    location: "620 10 Ave SW #134, Calgary, AB T2R 1C3 ",
    time: "4PM - 10PM (6 Hours)",
    fullTime: "Full-Time ",
    payment: "Payment: ",
    basicEnglish: "Basic English Needed",
    position: "3/5 positions filled",
    imageUrl: "/jobs/item.png",
    rate: "$18/hr",
    startDate: "Start Date: As soon as possible",
    title: "Server",
  },
];
